# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FuncScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StructScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(max_length=30)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.Dataset')),
            ],
        ),
        migrations.AddField(
            model_name='structscan',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.Subject'),
        ),
        migrations.AddField(
            model_name='funcscan',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.Subject'),
        ),
    ]
