# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='an',
            field=models.IntegerField(choices=[(1, 'T1w'), (2, 'T2w'), (3, 'PD')], default=1),
        ),
    ]
