# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_dataset_collection_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcscan',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='structscan',
            name='sub',
        ),
        migrations.AddField(
            model_name='subject',
            name='func_scan',
            field=models.FileField(default='test', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='struct_scan',
            field=models.FileField(default='test2', upload_to=b''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FuncScan',
        ),
        migrations.DeleteModel(
            name='StructScan',
        ),
    ]
