# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0004_subject_output_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='output_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
