# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcscan',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='structscan',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='dataset',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='FuncScan',
        ),
        migrations.DeleteModel(
            name='StructScan',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
